<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 11:16
 */

?>

<title><?php echo "";//echo $titulo ?> Inicio</title>
<link rel="shortcut icon" href="favicon.ico" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15" />
<meta http-equiv="content-language" content="es" />
<link href="<?php echo getHost(); ?>css/style.css"	title="Defaut" rel="stylesheet" type="text/css" media="screen" />
