<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 11:13
 */

?>

<div class="s_haut_menu">
Menu
</div><!-- DEBUT MeNu -->

<div class="s_fond_menu">
    <ul>
        <li ><a href="<?php echo getDirection(); ?>home/" title="">Inicio</a></li>
        <li ><a href="<?php echo getDirection(); ?>descargas/" title="">Descargas</a></li>
        <li ><a href="<?php echo getDirection(); ?>cuentas/" title="">Cuentas</a></li>
        <li ><a href="<?php echo getDirection(); ?>ladder/" title="">Ladder</a></li>
        <!--<li ><a href="<?php echo getDirection(); ?>soporte/" title="">Soporte</a></li>-->
    </ul>
</div>

<div class="s_bas_menu">

</div><!-- FIN MENU -->

<div class="s_haut_menu">Servidor</div><!-- DEBUT MENU -->
<div class="s_fond_menu">
    <?php
    ?>
    <div style="text-align: center;">
        <span>
            Estadisticas del servidor
        </span>
        <br/>
        <br/>
        <ul>
            <li>
                <strong>Cuentas Creadas :
                    <?php
                    echo (new Accounts())->getAccountSum();
                    ?>
                </strong>
            </li>
            <li>
                <strong>Personajes Creados :
                    <?php
                    echo (new Personajes())->getCantidadPersonajes();
                    ?>
                </strong>
            </li>
        </ul>
        <br/>
        <br/>
        <span>
            Servidor Realm:
        </span>
        <br/>
        <br/>

        <?php
        if(getServerStatus("127.0.0.1", 444)){
            echo '<img src="'.getDirection().'images/on.png">';
        }
        else{
            echo '<img src="'.getDirection().'images/off.png">';
        }
        ?>
        <br/>
        <br/>
        <span>
            Servidor Game:
        </span>
        <br/>
        <br/>

        <?php
        if(getServerStatus("127.0.0.1", 5555)){
            echo '<img src="'.getDirection().'images/on.png">';
        }
        else{
            echo '<img src="'.getDirection().'images/off.png">';
        }
        ?>
    </div>
</div>

<div class="s_bas_menu"></div><!-- FIN MENU -->
<a href="<?php echo getDirection(); ?>descargas/"><img src="<?php echo getDirection(); ?>images/telechargement.png" alt=""/></a><br />
<a href="<?php echo getDirection(); ?>cuentas/"><img src="<?php echo getDirection(); ?>images/inscription.png" alt=""/></a><br />
<!--<a href="inicio.php"><img src="images/forum.png" alt=""/></a><br />-->
<!-- FIN COLONNE DE GAUCHE -->
