<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 11:13
 */

?>

    <div class="s_haut_menu">
    Menu
    </div><!-- DEBUT MeNu -->

    <div class="s_fond_menu">
        <ul>
            <li ><a href="index.php" title="">Inicio</a></li>
            <li ><a href="descargas.php" title="">Descargas</a></li>
            <li ><a href="cuentas.php" title="">Cuentas</a></li>
            <li ><a href="ranking.php" title="">Ranking</a></li>
            <li ><a href="soporte.php" title="">Soporte</a></li>
        </ul>
    </div>

    <div class="s_bas_menu">

    </div><!-- FIN MENU -->

    <div class="s_haut_menu">Servidor</div><!-- DEBUT MENU -->
    <div class="s_fond_menu">
        <?php
        //include('mods/status.php');
        ?>
        <div style="text-align: center;">
            <span>
                Estadisticas del servidor
            </span>
            <br/>
            <br/>
            <ul>
                <li>
                    <strong>Cuentas Creadas :
                        <?php
                        /*$tcount = mysql_query("SELECT * FROM accounts");
                        echo mysql_num_rows($tcount);*/
                        echo (new Accounts())->getAccountSum();
                        ?>
                    </strong>
                </li>
                <li>
                    <strong>Personajes Creados :
                        <?php
                        /*$tchar = mysql_query("SELECT * FROM personnages");
                        echo mysql_num_rows($tchar);*/
                        ?>
                    </strong>
                </li>
            </ul>
            <br/>
            <br/>
            <span>
                Servidor:
            </span>
            <br/>
            <br/>

            <?php
                if(getServerStatus("127.0.0.1", 5555)){
                    echo '<img src="images/on.png">';
                }
                else{
                    echo '<img src="images/off.png">';
                }
            ?>
        </div>
    </div>

    <div class="s_bas_menu"></div><!-- FIN MENU -->
    <a href="config.rar"><img src="images/telechargement.png" alt=""/></a><br />
    <a href="cuentas.php"><img src="images/inscription.png" alt=""/></a><br />
    <a href="inicio.php"><img src="images/forum.png" alt=""/></a><br />
    <!-- FIN COLONNE DE GAUCHE -->
