<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 17:56
 */

?>

<h3>
    Todos los campos son Obligatorios!
</h3>
<br/>
<br/>
<div align="center">
    <span>
        Cuentas <?php echo "titre"//$titre; ?>:
    </span>
    <br/>
    <br/>

    <form action="<?php echo getHost(); ?>crearCuenta/" method="POST">
        <ul>
            <li>
                <div align="center">
                    <font color="black">
                        *Apodo:
                    </font>
                </div>
                <div class="Style10">
                    <p align="center">
                        <input type="text" name="pseudo">
                    </p>
                </div>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Cuenta:
                    </font>
                </div>
                <p align="center">
                    <input type="text" name="username">
                </p>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Contraseña:
                    </font>
                </div>
                <p align="center">
                    <input type="password" name="pass">
                </p>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Repite Contraseña:
                    </font>
                </div>
                <p align="center">
                    <input type="password" name="pass_confirm">
                </p>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Messenger:
                    </font>
                </div>
                <p align="center">
                    <input type="text" name="email"><br />
                </p>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Pregunta Secreta:
                    </font>
                </div>¿
                <p align="center">
                    <input type="text" name="question">
                </p>
            </li>
            <li>
                <div align="center">
                    <font color="black">
                        *Respuesta Secreta:
                    </font>
                </div>
                <p align="center">
                    <input type="text" name="reponse">
                    <br/>
                    <span style="font-size:xx-small;">

                    </span>
                </p>
            </li>
            <br/>
            <li>
                <center>
                    <input type="submit" value="Enviar" name="ok">
                </center>
            </li>
        </ul>
    </form>
    <br />
</div>
