<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 17:56
 */

?>

<h3>
    ¡Todos los campos son obligatorios!
</h3>
<br/>
<br/>
<div align="center">
    <span>
        Creacion de cuentas:
    </span>
    <br/>
    <br/>

    <div style="text-align: center; color:black;">
        <form action="<?php echo getHost(); ?>crearCuenta/" method="POST" onsubmit="return crearCuenta()">
            <table>
                <tr>
                    <td>
                        Nombre de cuenta:
                    </td>
                    <td>
                        <input type="text" id="username" name="username" title="username">
                    </td>
                </tr>
                <tr>
                    <td>
                        Contraseña:
                    </td>
                    <td>
                        <input type="password" id="pass" name="pass" title="pass">
                    </td>
                </tr>
                <tr>
                    <td>
                        Repita contraseña:
                    </td>
                    <td>
                        <input type="password" id="pass_confirm" name="pass_confirm" title="pass_confirm">
                    </td>
                </tr>
                <tr>
                    <td>
                        eMail:
                    </td>
                    <td>
                        <input type="text" id="email" name="email" title="email">
                    </td>
                </tr>
                <tr>
                    <td>
                        Apodo:
                    </td>
                    <td>
                        <input type="text" id="pseudo" name="pseudo" title="pseudo">
                    </td>
                </tr>
                <tr>
                    <td>
                        Pregunta secreta:
                    </td>
                    <td>
                        <input type="text" id="question" name="question" title="question">
                    </td>
                </tr>
                <tr>
                    <td>
                        Respuesta secreta:
                    </td>
                    <td>
                        <input type="text" id="reponse" name="reponse" title="reponse">
                    </td>
                </tr>
            </table>
            <br/>
            <input type="submit" value="Enviar" name="ok">
        </form>
    </div>
    <br />
</div>
