<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 18:41
 */

?>

<div align=center>
    <span>
        Descargas
    </span>
    <br/>
    <br/>

    <center>
        Haz Clic en el ugah para descargar la config.
    </center>
    <br/>

    <p>
        Descomprimir el .rar, el archivo .xml lo teneis que poner en donde tengas instalado Dofus
    </p>

    <p>EJE: C:/Archivos de programa/Dofus/</p>

    <a href="config.rar"><img src="<?php echo getDirection(); ?>images/Down.jpg"></a>

</div>
