<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 18:41
 */

?>

<div class="haut_ng">

</div><!-- GRAND CADRE-->
<div class="fond_ng">
    <div align=center>
        <span>
            Descargas
        </span>
        <br/>
        <br/>

        <center>
            Haz Clic en el ugah para descargar la config.
        </center>
        <br/>

        <p>
            Descomprimir el .rar, el archivo .xml lo teneis que poner en donde tengas instalado Dofus
        </p>

        <p>EJE: C:/Archivos de programa/Dofus/</p>

        <a href="config.rar"><img src="<?php echo getHost(); ?>images/Down.jpg"></a>

    </div>
</div>
<div class="bas_ng">

</div> <!-- FIN GRAND CADRE-->

<div class="separateur">

</div>
