<?php
/**
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 11:30
 */

?>

<div class="haut_ng">

</div><!-- GRAND CADRE-->

<div class="fond_ng">
    <div align=center>
        <span>
            Noticias!!
        </span>
        <br/><br/>
        <ul>
            <li>Noticia 1.</li>

            <li>Noticia 2!</li>
            <li>Noticia 3</li>
        </ul>

    </div>
</div>
<div class="bas_ng">

</div> <!-- FIN GRAND CADRE-->

<div class="separateur">

</div>
 <!-- FIN COLONNE DE DROITE -->
