<?php
/**
 * Created by PhpStorm.
 * User: Anghelo
 * Date: 17-11-2016
 * Time: 19:06
 */

?>

<div align=center>
    <span>Ranking</span>
    <br/>
    <br/>

    <table>
        <tr>
            <th>
                Personaje
            </th>
            <th>
                Clase
            </th>
            <th>
                Nivel
            </th>
            <th>
                Experiencia
            </th>
        </tr>
        <?php
        foreach((new Personajes())->getPersonajesOrdenadosNivel() as $key => $value){
            echo "<tr>";
                echo "<td>";
                    echo $value["name"];
                echo "</td>";
                echo "<td>";
                    echo getClase($value["class"]);
                echo "</td>";
                echo "<td>";
                    echo $value["level"];
                echo "</td>";
                echo "<td>";
                    echo $value["xp"];
                echo "</td>";
            echo "</tr>";
        }
        ?>
    </table>

    <br/>
</div>
